### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by vapor99** [marius311/boinc-server-docker#1]
This was very helpful for me.  Much appreciated

**Comment by marius311** [comment]
Cool thanks, this is still very early in development, you were able to get it up and running?

**Comment by vapor99** [comment]
> On Jul 20, 2015, at 2:33 PM, Marius Millea <notifications@github.com> wrote:
> 
> Cool thanks, this is still very early in development, you were able to get it up and running?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/marius311/boinc-server-docker/issues/1#issuecomment-122979919>.
> 
Ya, I had to clone the boinc repo into the boinc folder before running docker-compose make_project and it worked well.  I am making a python project using py2exe and genwrapper with oclHashcat for distributed.  I think boinc will work for this as I need to use the GPU and/or CPU in combination for the fastest execution.  Pretty neat stuff!
