### ISSUE TITLE
/bin/sh: 1: ./_autosetup: not found

### ISSUE THREAD

**Issue by grctest** [marius311/boinc-server-docker#12]
Error:
```
Step 4 : COPY boinc /root/boinc
 ---> f55b8d9f00f5
Removing intermediate container 9f5723a5fb2b
Step 5 : RUN cd /root/boinc && ./_autosetup && ./configure --disable-client --disable-manager && make
 ---> Running in 733335984fdb
/bin/sh: 1: ./_autosetup: not found
ERROR: Service 'makeproject' failed to build: The command '/bin/sh -c cd /root/boinc && ./_autosetup && ./configure --disable-client --disable-manager && make' returned a non-zero code: 127
```

Installed docker-compose version 1.8, ran the 'docker-compose up -d' command during the test project setup, encountered the above error.

**Comment by grctest** [comment]
Just spotted that Neuralminer posted a pull request for this https://github.com/marius311/boinc-server-docker/pull/11

**Comment by vladfi1** [comment]
I am seeing this issue on a first-time install on Ubuntu 18.04, even right after executing `docker-compose pull`.

**Comment by marius311** [comment]
Can you verify you have the submodules checked out as described [here](https://github.com/marius311/boinc-server-docker/tree/0b2aa93e2050980c66a90c55bdebab00afe70691#development-and-contributing) ?

**Comment by vladfi1** [comment]
If I re-clone the repo with `--recursive` it works fine. I was following [this section](https://github.com/marius311/boinc-server-docker/blob/master/docs/cookbook.md#launching-a-test-server) of the guide which doesn't mention submodules.

**Comment by marius311** [comment]
That's odd, this error should only happen when building the images, and I don't think the `pull` then `up` commands should trigger a build. But it sounds like in your case they are?
