### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by grctest** [marius311/boinc-server-docker#15]
I've been trying to add SSL support to my test BOINC project but have been unable to open port 443 fully to the public.

I've tried:
* Opening port 443 (ipv4 & ipv6) via UFW on the host vm.
* "a2enmod ssl" within the Apache container
* Enabled SSL in the /etc/apache2/sites-available/ along with project specific config.
* "iptables -A INPUT -p tcp --dport 443 -j ACCEPT" (on host vm, no luck).

I'm going to try next:
"Expose port" in the Apache dockerfile https://docs.docker.com/engine/reference/builder/#/expose

Any tips/tricks/hints? 

Cheers

**Comment by MTRNord** [comment]
Look at this line. Maybe there is 443 needed: https://github.com/marius311/boinc-server-docker/blob/master/docker-compose.yml#L45

**Comment by grctest** [comment]
@MTRNord Thanks, this fixed the blocked 443 port issue and I was then able to issue SSL certificate using letsencrypt's certbot :)

**Comment by marius311** [comment]
Great, glad you figured it out. If there's any of what you've set up that you think coud be part of boinc-server-docker, please don't hesitate to PR, I've always thought it'd be great to have SSL an option which would be easy to enable here. 

Also not sure what CA you used, but LetsEncrypt is easy/free/has a Docker image setup option, so it could potentially work together really nicely, although I haven't thought about it enough to know exactly what it would look like.

**Comment by grctest** [comment]
I used EFF's certbot certbot.eff.org

I needed to create a new config for the domain  /etc/apache2/sites-available/websitedomain.tld.conf which was just a copy of the 000-default.conf file with the addition of the following lines:
```
    ServerAdmin admin@test.com
    ServerName test.com
    ServerAlias www.test.com
```

I basically followed this guide: https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts

The boincserver.httpd.conf file was rejected by certbot.

You're right that they have a docker image setup option: https://github.com/certbot/certbot/blob/master/Dockerfile But I'm pretty new to docker & didn't know how an external docker container would interact with the apache container, going to look into docker to get a better understanding.
