### ISSUE TITLE
Docker run command does not terminate

### ISSUE THREAD

**Issue by hzclarksm** [marius311/boinc-server-docker#17]
I am using the simple example given in the cookbook:

`# bin/boinc2docker_create_work.py \
    python:alpine python -c "print('Hello BOINC')"`

[stderr.txt](https://github.com/marius311/boinc-server-docker/files/562518/stderr.txt)

**Comment by marius311** [comment]
Can you check that's the entire stderr log? It looks like there might me more that cut off. 

Also, can you tell me your client, Virtualbox, and OS versions?

**Comment by marius311** [comment]
Ah, right, your Virtualbox version is in that stderr log (its 4.1.42). I would try upgrading to Virtualbox 5.X and see if this still occurs.

**Comment by hzclarksm** [comment]
Upgrading to VirtualBox 5.1.8 from Debian jessie-backports solved the problem.
