### ISSUE TITLE
Upgrading and misc issues

### ISSUE THREAD

**Issue by marius311** [marius311/boinc-server-docker#19]
From @davidpanderson:

Marius:
Steve Clark and I were working with a container-based BOINC server and we ran into a snag:
we need to update the server software in the main container.
In order to do this, the container needs to have:
- git
- a copy of the BOINC repo
- all the gnu tools (gcc, autoconf, etc)
- a text editor

It looks like you made the container fairly stripped-down to minimize size.
But in this case size isn't a big concern.

Other issues:

- It looks like make_project creates a download directory that's owned by root
and is not writable by the Apache user (www-data);
it needs to be writable remote file management to work.

- It looks like there's an assumption that the container has a single project, in /project.
Some of the BOINC tools (like "upgrade") assume that projects are subdirectories
of ~/projects.

**Comment by hzclarksm** [comment]
The download directory simply needs to have group write permission added. The www-data user is a member of group root.

**Comment by marius311** [comment]
> Steve Clark and I were working with a container-based BOINC server and we ran into a snag:
we need to update the server software in the main container.
In order to do this, the container needs to have:
>
>git
a copy of the BOINC repo
all the gnu tools (gcc, autoconf, etc)
a text editor
It looks like you made the container fairly stripped-down to minimize size.
But in this case size isn't a big concern.

As you have probably seen, the server software is [compiled](https://github.com/marius311/boinc-server-docker/blob/ed9db3f2df49f57596b81ecef36198dfe56f7f5a/images/makeproject/Dockerfile#L24) while building the `makeproject` image, based on the source code in the boinc/ submodule in [this](https://github.com/marius311/boinc-server-docker/tree/master/images/makeproject) folder. Also during the build, the new project is [installed](https://github.com/marius311/boinc-server-docker/blob/ed9db3f2df49f57596b81ecef36198dfe56f7f5a/images/makeproject/Dockerfile#L31) into a folder in the image's filesystem at `/root/project`. When *run*, the `makeproject` container then copies these files into the Docker "project" volume which contains your actual project's files and is mounted at `/root/project` in your Apache container. 

The intended way to upgrade is then to update that BOINC submodule, rebuild the makeproject image, then run it so that it copies new files over into your project folder. If, as recommended, you've created a custom `makeproject` image for your project which sources from the official `boinc/server_makeproject` one (e.g. [here](https://github.com/marius311/cosmohome/blob/master/Dockerfile)), then you yourself ideally never have to do anything. You simply upgrade the version of `boinc/server_makeproject` which you have pinned in your Dockerfile. 

That said, that `tools/upgrade` script also updates the DB and translations, which if they're necessary for now you may have to do by hand. I'll work on fixing that. Also, this should be documented. 

> It looks like make_project creates a download directory that's owned by root
and is not writable by the Apache user (www-data);
it needs to be writable remote file management to work.

Good catch, thanks. I missed this since I've never used the remote file management. Will commit fix shortly. 

> It looks like there's an assumption that the container has a single project, in /project.
Some of the BOINC tools (like "upgrade") assume that projects are subdirectories
of ~/projects.

Yes, (/root/project in fact), but all these types of scripts can take an argument for the project_root, no? 

One project / container was a design choice by me in order to have boinc-server-docker work as much as possible out-of-the-box. If you want multiple projects per host for testing, there's nothing stopping you from running multiple copies of these containers, you'll just have to manually tweak the port mapping since both containers can't have port 80. If you really want multiple projects inside one container, it can be done, let me know I'll describe further.

**Comment by marius311** [comment]
> The download directory simply needs to have group write permission added. The www-data user is a member of group root. 

Correct, that's probably the route I'll go for now. (see also https://github.com/marius311/boinc-server-docker/issues/14 for anyone curious on more discussion on use of root accounts)

**Comment by marius311** [comment]
The download permission is error is now fixed in https://github.com/marius311/boinc-server-docker/commit/a6584e63c17c364b170d76f209c48b9de3138e63. Closing this issue for now, but feel free to use to discuss anything else here further.
