### ISSUE TITLE
How do I change de hard coded URL?

### ISSUE THREAD

**Issue by davidcalle9430** [marius311/boinc-server-docker#2]
I tried scanning the repository and changed them all but it still doesnt work when you sign in

**Comment by marius311** [comment]
Hi David, I'm assuming you're following the directions from [docs/example_project.md](https://github.com/marius311/boinc-server-docker/blob/master/docs/example_project.md). You will need to,

* Change the various `<url>` tags in `config.xml`
* Change the `boincserver.httpd.conf` file 

You can take a look at Cosmology@Home's [config.xml](https://github.com/marius311/cosmohome/blob/master/config.xml) and [httpd.conf](https://github.com/marius311/cosmohome/blob/master/boincserver.httpd.conf) as an example.

**Comment by davidcalle9430** [comment]
Thank you for your quick response, I'm still just getting started with Boinc and theres so much i don't know, any documentation you would recommend?

**Comment by marius311** [comment]
Np. I think https://boinc.berkeley.edu/trac/wiki/ProjectMain is a good place to start for creating a project. There's admittedly a lot to know. Be aware that those instruction don't use boinc-server-docker, so a number of things mentioned in there as necessary to set up a project have already been done for you.
