### ISSUE TITLE
Feature request: add variables to server_makeproject image

### ISSUE THREAD

**Issue by zarbis** [marius311/boinc-server-docker#20]
Hi, I'm trying out your dockerized boinc and it seems to work just fine except one little moment.
Image `boinc/server_makeproject` uses hardcoded parameters.
It would be really good for automation if they were defined as evironment variables like `$PROJHOME` you already have.

In that case you can generate ready-to-run projects like:
`docker run --rm -e URL_BASE=http://myserver.net -e DB_HOST=some_mysql_container .... boinc/server_makeproject`

**Comment by marius311** [comment]
That's a great idea, I like it a lot. I'll have to think exactly how to handle the fact that server_makeproject gets run every time you bring the server up, and what to do if e.g. you change the URL from one run to the next, but it seems doable and I'll look into it.

**Comment by marius311** [comment]
Only took a year but `URL_BASE` is added by c87ec6f636dc5653b3c5699d4b316fff81d96e97 :tada: 

I'm curious to get feedback if you are still interested in this and get a chance to look.

`DB_HOST` could perhaps be added, although what exactly would be the use-case / what would you want it to do exactly?

**Comment by marius311** [comment]
Closed by https://github.com/marius311/boinc-server-docker/pull/43
