### ISSUE TITLE
Unable to find results.tgz

### ISSUE THREAD

**Issue by gadkins** [marius311/boinc-server-docker#21]
Great project! I'm not sure if this is an issue or if I'm just confused. I followed your setup and ran through you basic cookbook examples successfully, but I'm having trouble with the following:

root@boincserver:~/project# bin/boinc2docker_create_work.py \
    python:alpine python -c "open('/root/shared/results/hello.txt','w').write('Hello BOINC')"

My BOINC client is able to download and execute the above command, and from the boincserver_ops admin page I can see the stderr out:
...
Guest Log: Saving results...
Guest Log: hello.txt
...

but I'm not able to find this file. My understanding is that hello.txt should be zipped in a file called results.tgz and found in the /results volume of my Apache server (accessed via make exec-apache). However, I'm not seeing it. Is it somehow being deleted? Am I missing something?

**Comment by marius311** [comment]
You're right, this doesn't appear to be working automatically. You'll need to add

```xml
<daemon>
    <cmd>script_assimilator --app boinc2docker --script "boinc2docker_assimilator files"</cmd>
</daemon>
<daemon>
    <cmd>sample_trivial_validator -app boinc2docker</cmd>
</daemon>
```
to the `<daemons>` section of your projects `config.xml`, then running a `bin/restart`. After that you should see the result files appear in `/results/boinc2docker` (they're not called `results.tgz` they have a funny long name but they're tar files and will contain the hello.txt file). 

This should be done automatically for you, I'll work on getting a fix in.

**Comment by gadkins** [comment]
Yep, that worked. Thanks.

**Comment by marius311** [comment]
This is now fixed in https://github.com/marius311/boinc2docker/commit/ef4819437574d71e9f05f045927e2c8b6499006d, and current master of boinc-server-docker is updated to include that commit.
