### ISSUE TITLE
When upgrading BOINC web server via recompiling - how do you ensure persistent server data?

### ISSUE THREAD

**Issue by grctest** [marius311/boinc-server-docker#23]
Hey @marius311,

I make changes to the core BOINC web server ([Project-Rain](https://github.com/BOINC/boinc/issues/1998)) which require that I self-compile the BOINC web server, given that when you fully stop the docker container the contents of the container are lost, how do I ensure that the mysql databases don't get destroyed when I'm only wanting to uplift the web server code?

Effectively, how do I ensure data persistence for the mysql container when upgrading the core BOINC web server?

Best regards,
CM.

**Comment by marius311** [comment]
There's three Docker volumes that house the data for your project. Once you've got the server up you can see them with

```
$ docker volume ls
DRIVER              VOLUME NAME
local               boincserverdocker_mysql
local               boincserverdocker_project
local               boincserverdocker_results
```

The `boincserverdocker_mysql` one has the database. As long as you don't delete this volume, your database persists, and the mysql container, even after stopping/starting it or even upgrading the image itself will always just use this.

The way to delete these volumes is with `docker volume rm $NAMEOFVOLUME`, or if you do `docker-compose down -v` (the `-v` specifies to delete the volumes associated with the docker-compose file in question).
