### ISSUE TITLE
Outdated docker client version

### ISSUE THREAD

**Issue by gadkins** [marius311/boinc-server-docker#24]
I noticed after entering the apache shell via `make exec-apache` that the docker client version is quite outdated. From inside the shell, if I run `docker version` I get the following output:

`Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
`

On my host machine I am currently using version 17.06.1-ce for both client and server. There have been many improvements and added features since version 1.10.3. How can I keep the client version up-to-date? I tried using the latest version of boot2docker, but that didn't seem to help. Thanks!

**Comment by marius311** [comment]
The client is installed into the Apache container [here](https://github.com/marius311/boinc-server-docker/blob/b4d09a699e88871fea503836af343adf29a96f60/images/apache/Dockerfile.b2d#L28), it would just need to be updated there, or alternatively in your custom Apache Dockerfile just delete than and overwrite with a newer version. 

I haven't done so only because I haven't needed it and haven't had time to test newer versions, but I can look into it. Out of curiosity, any new features or problems with the old version driving you to upgrade?

**Comment by gadkins** [comment]
I tried updating the version as you recommended, but I'm having trouble finding the correct path to the current version with `get.docker.com.` Instead, I successfully installed the current version with the [convenience script](https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script) using the follow commands:

`RUN curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh`

However, this seems to cause problems when running:
 `bin/boinc2docker_create_work python:alpine python -c "print('Hello BOINC')`

I get the following error:

  File "bin/boinc2docker_create_work.py", line 357, in <module>
    force_reimport=args.force_reimport)
  File "bin/boinc2docker_create_work.py", line 101, in boinc2docker_create_work
    image_size = get_image_size(image)
  File "bin/boinc2docker_create_work.py", line 253, in __getitem__
    return dict.__getitem__(self, key)
  File "bin/boinc2docker_create_work.py", line 255, in __missing__
    ret = self[key] = f(*key)
  File "bin/boinc2docker_create_work.py", line 281, in get_image_size
    val, units = output[0].split()
ValueError: need more than 1 value to unpack

I want to upgrade because I'd like to run some experiments using `docker swarm` which was implemented in version 1.12.

**Comment by marius311** [comment]
Yea, looks like some aspect of the "docker inspect" command or its return changed in this version so the boinc2docker_create_work script would need to be updated. I will take a look, but honestly I probably don't have time for a couple of weeks. I'm happy to accept PRs if you're interested though!

**Comment by gadkins** [comment]
Your theory was correct. The docker client image size format has changed to include no whitespace between the value and the units. For example, ['80 MB'] is now ['80MB'] in newer versions of the client. I made two small changes to provide compatibility for either format. PR is submitted to marius311/boinc2docker.

**Comment by marius311** [comment]
Fixed by https://github.com/marius311/boinc2docker/pull/9
