### ISSUE TITLE
Boinc client don't see tasks on server

### ISSUE THREAD

**Issue by diozdeath19** [marius311/boinc-server-docker#28]
Hi marius, i've small problem. I run boinc server and submit tasks. You can see this in the picture below
![_013](https://user-images.githubusercontent.com/25438889/36442366-9dd58634-1686-11e8-86a8-eac011ea4390.png)
But i don't see tasks on client via BOINC Manager or boinccmd, boinccmd tells me that no task on server
![_014](https://user-images.githubusercontent.com/25438889/36442466-e988cdde-1686-11e8-8981-caf7f15c0453.png)
I've ubuntu 16.04 with installed VirtualBox and enabled virtualization. BOINC Manager tells that VirtualBox not installed, although i installed her, maybe it's related. Sorry for bad english)

**Comment by marius311** [comment]
If the BOINC Manager thinks VirtualBox is not installed then that's definitely the problem, the server won't send any jobs if it thinks the client won't be able to run them. I think the problem of VirtualBox not being detected is somewhat typical, so you may find some ideas what's going wrong via Google and the BOINC message boards, but I'm afraid I don't have very good suggestions for where to start looking.
