### ISSUE TITLE
Unable to build server

### ISSUE THREAD

**Issue by TheAspens** [marius311/boinc-server-docker#45]
I tried to do a clean build of  a server using the instructions:

- git clone https://github.com/marius311/boinc-server-docker.git
- cd boinc-server-docker
- docker-compose build --no-cache
- docker-compose up -d

And a few issues emerged on the "docker-compose build --no-cache"  step.

1. boinc-server-docker/images/makeproject/boinc is empty and thus there is nothing to build
2. If I checkout boinc to fill that directory, and repeat docker-compose build --no-cache, I then get 

```
Removing intermediate container a467df53a87a
 ---> 49e0a3045cb8
Step 13/32 : COPY boinc2docker /root/boinc2docker
 ---> 798be3ebf02c
Step 14/32 : RUN /root/boinc2docker/boinc2docker_create_app --download_only
 ---> Running in 942b4f2c0bb7
/bin/sh: 1: /root/boinc2docker/boinc2docker_create_app: not found
ERROR: Service 'makeproject' failed to build: The command '/bin/sh -c /root/boinc2docker/boinc2docker_create_app --download_only' returned a non-zero code: 127

```

Is there something I should be doing different?

**Comment by marius311** [comment]
To build the images rather than just run them you need to clone with `--recursive`. Alternatively if you cloned without that, do `git submodule update --init --recursive` to grab all the submodules (the error you're seeing is probalby because the boinc2docker submodule was not checked out)
