### ISSUE TITLE
Signature Error

### ISSUE THREAD

**Issue by MTRNord** [marius311/boinc-server-docker#5]
When using boinc2docker to generate work the client says 
`10.07.2016 11:26:26 | ProjectStreet | [error] Signature verification error for boinc2docker_1.03_vbox_job.xml` 
and
 `10.07.2016 11:26:26 | ProjectStreet | [error] Checksum or signature error for boinc2docker_1.03_vbox_job.xml`

 Where can I fix that?

**Comment by MTRNord** [comment]
It seems I had manually to resign every file

**Comment by marius311** [comment]
Hi, can you give me the list of steps with which you create the project / add you app / sign things? 

Btw, there's a work in progress documentation here https://github.com/marius311/boinc-server-docker/blob/master/docs/cookbook.md which might be helpful. Apologies the docs are not yet in a more mature state, I'm working on them, don't hesitate to email me directly if you have any further questions!

**Comment by MTRNord** [comment]
I created it with boinc2docker like in the example. But the client gave me the eroor above. I needed to fix the `bin/sign_all_apps` file (there is one path incorrect). and than I ran it. After that it runs fine without any problem. (client don't have sign and checksum error)

**Comment by marius311** [comment]
Can you give me the list of commands you ran? You shouldn't need any manual resigning. For example, 

```
$ docker-compose up -d
$ docker exec -it boincserverdocker_apache_1 bash
root@boincserver:~/project# bin/boinc2docker_create_work.py mtrnord/docker-benchmark:latest sh -c "sysbench --debug --test=threads > /root/shared/results/benchmark.txt"
```

should work. I'm guessing you've done something differently. 

Note that if you've made changes in the project directory, these stick around after you do a `docker-compose down` and could be what's messing things up.  To completely reset the project directory, you should do a `docker-compose down -v` (the `-v` deletes the Docker volumes holding the project directory and mysql database), then next time you do `up -d` the project directory will get recreated.

**Comment by MTRNord** [comment]
I did following to get it working:

1. Fix the path in `bin/sign_all_apps` on the apache volume

2. I ran the following (note the second command directly after running boinc2docker)
```
$ make exec-apache
root@boincserver:~/project# bin/boinc2docker_create_work.py mtrnord/docker-benchmark:latest sh -c "sysbench --debug --test=threads run > /root/shared/results/benchmark.txt" && bin/sign_all_apps
```

**Comment by marius311** [comment]
What do you mean "fix the path" in bin/sign_all_apps?

**Comment by MTRNord** [comment]
in "bin/sign_all_apps" where an file ran in an path that was wrong. The file that will be run in the "bin/sign_all_apps" isn't in the path that is written in "bin/sign_all_apps". The correct path has to be the bin dir in the project folder and not the tools folder

**Comment by marius311** [comment]
So I think the confusion stems from the fact that `sign_all_apps` should only be called from inside your custom `makeproject` container, not from the running `apache` container. For example, like so: https://github.com/marius311/cosmohome/blob/master/Dockerfile#L30

The idea (which I'm working on documenting better) is that you create your entire project folder (which includes creating / installing / signing custom apps) from inside your customized `makeproject` image, that way its reproducible and easy to see the list of commands in the `Dockerfile` as above. 

I'm still not entirely sure why you're getting a signing error through. If you start from a fresh project folder (i.e. after a `docker-compose down -v`), then run a `docker-compose up -d`, the `boinc2docker` app should be signed correctly. You must be running some other commands somewhere?

**Comment by MTRNord** [comment]
I did pulled the git a few weeks back and don't use the example dir. I use the root folder. I only did go into the apache server and run boinc2docker. maybe it is just because i run that directly in the container

**Comment by marius311** [comment]
Can you post the output from first resetting your project folder / database with:

```
$ docker-compose down -v
```

then recreating the server and submitting your job:

```
$ docker-compose up -d
$ docker exec -it boincserverdocker_apache_1 bash
root@boincserver:~/project# bin/boinc2docker_create_work.py mtrnord/docker-benchmark:latest sh -c "sysbench --debug --test=threads run > /root/shared/results/benchmark.txt"
```

At this point there should be no signature errors, but you will get the error here https://github.com/marius311/boinc-server-docker/issues/6. I've got a workaround for that almost ready, btw.

**Comment by MTRNord** [comment]
To note: my git commit using is: `66c4ea054e07ceb0f7cffef7bf64c3d0e8a50c68`

log from reset:
```
root@debian:/home/marcel/boinc-server-docker-ProjectStreet# docker-compose down -v
Stopping boincserverdockerprojectstreet_apache_1 ... done
Stopping boincserverdockerprojectstreet_mysql_1 ... done
Removing boincserverdockerprojectstreet_apache_1 ... done
Removing boincserverdockerprojectstreet_mysql_1 ... done
Removing volume boincserverdockerprojectstreet_project
Removing volume boincserverdockerprojectstreet_results
Removing volume boincserverdockerprojectstreet_mysql
```
starting:

```
root@debian:/home/marcel/boinc-server-docker-ProjectStreet# docker-compose up -d
Creating volume "boincserverdockerprojectstreet_project" with default driver
Creating volume "boincserverdockerprojectstreet_results" with default driver
Creating volume "boincserverdockerprojectstreet_mysql" with default driver
Creating boincserverdockerprojectstreet_mysql_1
Creating boincserverdockerprojectstreet_makeproject_1
Creating boincserverdockerprojectstreet_apache_1
```

boinc2docker command:

```
root@debian:/home/marcel/boinc-server-docker-ProjectStreet# docker exec -it boincserverdockerprojectstreet_apache_1 bash
root@ProjectStreet:~/project# bin/boinc2docker_create_work.py mtrnord/docker-benchmark:latest sh -c "sysbench --debug --test=threads run > /root/shared/results/benchmark.txt"
Exporting 'mtrnord/docker-benchmark:latest' to tar file...
Creating input file for layer 8d6aa3555d3a...
Creating input file for layer de485ad86340...
Creating input file for layer bced535a7943...
Creating input file for layer ffda786f2dcc...
Creating input file for layer 8a826a960470...
Creating input file for layer 37be6edc936b...
Creating input file for layer c5b76880fa89...
Creating input file for layer 6d3f50157254...
Creating input file for layer 1b823e7c5bb4...
Creating input file for image 060f382a80df...
Creating input template for job...
workunit name: boinc2docker_160_1468863228.245949
```

**Comment by MTRNord** [comment]
The signature errors came up when the client tries to download the files

**Comment by marius311** [comment]
I notice you changed the hostname to `ProjectStreet`. Any other changes you've made? That could be the source.

**Comment by MTRNord** [comment]
I changed the hostname in any field where an hostname was defined in the git. so that it should (at least i think so) should make no problem but that is only a beauty thing.

**Comment by MTRNord** [comment]
(It worked with an clean install

**Comment by MTRNord** [comment]
On windows it seems like the bug ist back.

In the Client this comes up:

```
30.09.2016 08:31:12 |  | Suspending computation - user request
30.09.2016 08:34:29 |  | Fetching configuration file from http://projectstreet.dynu.com/ProjectStreet/get_project_config.php
30.09.2016 08:34:41 | ProjectStreet | Scheduler request completed: got 1 new tasks
30.09.2016 08:34:43 | ProjectStreet | Started download of vboxwrapper_26186_windows_x86_64.exe
30.09.2016 08:34:43 | ProjectStreet | Started download of boinc2docker_1.04_vbox_job.xml
30.09.2016 08:34:44 | ProjectStreet | Finished download of vboxwrapper_26186_windows_x86_64.exe
30.09.2016 08:34:44 | ProjectStreet | Finished download of boinc2docker_1.04_vbox_job.xml
30.09.2016 08:34:44 | ProjectStreet | Started download of vm_isocontext_v1.0.0.iso
30.09.2016 08:34:44 | ProjectStreet | Started download of boinc_app_03a3629cc4e94bb0a75d6c0963d6b82d
30.09.2016 08:34:44 | ProjectStreet | [error] Signature verification error for vboxwrapper_26186_windows_x86_64.exe
30.09.2016 08:34:44 | ProjectStreet | [error] Checksum or signature error for vboxwrapper_26186_windows_x86_64.exe
30.09.2016 08:34:44 | ProjectStreet | [error] Signature verification error for boinc2docker_1.04_vbox_job.xml
30.09.2016 08:34:44 | ProjectStreet | [error] Checksum or signature error for boinc2docker_1.04_vbox_job.xml
30.09.2016 08:34:45 | ProjectStreet | Finished download of vm_isocontext_v1.0.0.iso
30.09.2016 08:34:45 | ProjectStreet | Finished download of boinc_app_03a3629cc4e94bb0a75d6c0963d6b82d
30.09.2016 08:34:45 | ProjectStreet | Started download of layer_d63f44964b3c7dff03cdfa5f91de668e57e2afdb41e6d6de3b1dbdfaf305932b.tar
30.09.2016 08:34:45 | ProjectStreet | Started download of image_1b088884749bd93867ddb48ff404d4bbff09a17af8d95bc863efa5d133f87b78.tar
30.09.2016 08:34:47 | ProjectStreet | Finished download of image_1b088884749bd93867ddb48ff404d4bbff09a17af8d95bc863efa5d133f87b78.tar
30.09.2016 08:34:48 | ProjectStreet | Finished download of layer_d63f44964b3c7dff03cdfa5f91de668e57e2afdb41e6d6de3b1dbdfaf305932b.tar

```

On server side I ran that:

```
root@ProjectStreet:~/project# bin/boinc2docker_create_work.py python:alpine python -c "print('Hello BOINC')"
Pulling 'python:alpine'...
Image already imported into BOINC. Reading existing info...
Creating input template for job...
workunit name: boinc2docker_80_1475217231.488161
```

**Comment by MTRNord** [comment]
Adding `&& bin/sign_all_apps` also did not help

**Comment by marius311** [comment]
Usually that's a sign that somehow the files `vboxwrapper_26186_windows_x86_64.exe` and `boinc2docker_1.04_vbox_job.xml` got changed *after* having installed them into the downloads folder with `bin/update_versions` (which is run automatically every time you do a `docker-compose up -d`). Another possibility is your public/private keys changed so the signature no longer matches. 

Check the output of `bin/sign_executable download/vboxwrapper_26186_windows_x86_64.exe keys/code_sign_private` against what's in the database under the app_version table in the appropriate place. Probably you'll see its different. 

The simple way to fix this is do a `docker-compose down -v`. This will (warning!) delete your project/database/results volumes (which presumably since you're just testing/developing is fine), but then when you do the following `up -d` it should set up everything correctly and cleanly. 

As for how it got that way, I'm not 100% sure. One suggestion I have glancing at your code is you should consider rather than forking the boinc-server-docker repo and editing the Dockerfiles, just to create your own set of Dockerfiles based on the provided boinc-server-docker ones. See Cosmology@Home for an [example](https://github.com/marius311/cosmohome/blob/master/Dockerfile) and the (work in progress) [cookbook](https://github.com/marius311/boinc-server-docker/blob/master/docs/cookbook.md) for a bit more explanation. This'll make it easier to stay up-to-date with the latest boinc-server-docker version, and its the intended way I had in mind for people to use this.

**Comment by MTRNord** [comment]
I am doing that fork mainly because I am working on an arm version for it :) So I need to change the base images later (therefor I also build nodejs in the apache docker and things like that).

I will try to test that

**Comment by marius311** [comment]
Ah interesting, I didn't look around enough to see that. ARM meaning being able to submit Docker ARM images for jobs? Or running the server itself on ARM?

**Comment by MTRNord** [comment]
I got another fork under this Profil (MTRNord) with an arm tree (WIP). Thats because I want to port it onto resin.io / Raspberry Pi. Because the Server itself doesn't require a lot of power. So I decided (because I got an IPv6 network) why not just use an Raspberry Pi as Server. But therefor it has to use arm as arch. That one under Nordgedanken is just the non arm version of the same project.

**Comment by MTRNord** [comment]
Link to my fork for arm (is on and older base fork build): https://github.com/MTRNord/boinc-server-docker-resin-arm/tree/rpi

**Comment by MTRNord** [comment]
So after fresh clone it got even worse. Now it is unable to find Boinc2docker. I think I have to refork your project and Start from scratch. Maybe I broke the submodules when I merged the last update...

**Comment by marius311** [comment]
What's the error. You cloned with `--recursive`?

**Comment by MTRNord** [comment]
Yes i did but it says File not found. I did an failed merge before that broke the submodules. I thaught ist had fixed the submodules . But seems like it did not fix it. :/ Problem from me i think

**Comment by MTRNord** [comment]
boinc2docker bug was because I accidently deleted somehow some lines in the Dockerfile xD :
```
# create boinc2docker app
COPY boinc2docker /root/boinc2docker
ENV PATH=/root/boinc2docker:$PATH
# the vboxwrapper/iso/appver installed will be taken from boinc2docker/boinc2docker.yml
RUN boinc2docker_create_app
```

**Comment by MTRNord** [comment]
After I readded that it does work :) seems like I did break the submodules
