### ISSUE TITLE
Build errors when testing with python 3

### ISSUE THREAD

**Issue by TheAspens** [marius311/boinc-server-docker#57]
@davidpanderson and @lfield are working on migrating BOINC to python3.  See https://github.com/BOINC/boinc/pull/2477

boinc-server-test tries to run its tests against that branch but fails at this step:

```
Step 1/1 : RUN test -z "$TAG" || boinc2docker_create_app --projhome $PROJECT_ROOT
 ---> Running in 28d9ba77d2f5
Traceback (most recent call last):
  File "/boinc2docker/boinc2docker_create_app", line 185, in <module>
    xmlmerge(src,join(args.projhome,f),idkey=k,mergeat=m)
  File "/boinc2docker/boinc2docker_create_app", line 164, in xmlmerge
    if dc.find(idkey).text==sc.find(idkey).text: break
AttributeError: 'NoneType' object has no attribute 'text'
```

Would you be able to resolve the issue with this step or provide a flag so that I can skip the step of adding boinc2docker to the docker images when I'm building them for boinc-server-test?

Thanks!
- Kevin

**Comment by davidpanderson** [comment]
I'm not sure what the issue is.  #2477 is a dead-end;
supporting Python 3 is a bigger job than I first thought.

**Comment by TheAspens** [comment]
@davidpanderson - you still have https://github.com/BOINC/boinc/pull/2477 open and @lfield is looking to get it merged.  Can you follow up with him on that pull request to discuss?

@marius311 - it would still be helpful if I could have a command line option that would allow me to skip loading boinc2docker when I build the images for the boinc-server-test project.

**Comment by marius311** [comment]
> @marius311 - it would still be helpful if I could have a command line option that would allow me to skip loading boinc2docker when I build the images for the boinc-server-test project.

It's:

```
TAG="" docker-compose build
```

(see also https://github.com/marius311/boinc-server-docker/blob/master/docs/cookbook.md#running-without-boinc2docker)

**Comment by TheAspens** [comment]
Thanks @marius311 - that did the trick.
