### ISSUE TITLE
boinc_submit does not work within toolbox

### ISSUE THREAD

**Issue by madformuse** [marius311/boinc-server-docker#58]
I'm just starting out trying to develop a project and in an attempt to get testing as fast as possible I've been trying to use the boinc_submit script. 

The container is obviously Linux but I'm wanting to target my windows desktop client so I've not been able to use the single_job_setup script, opting instead to manually create the single_job structure within apps for my platform as per instructions on BOINC site.

The problem is I'm getting a database error when attempting to run the boinc_submit script. After jumping into the source I managed to discover that the problem is it's attempting to insert a workunit, specifying only the name and transition time. The error relates to the lack of a default value for the create_time field. Unfortunately once I'd manually provided the value for that field (converting PHP date to Unix epoch), it only led to the same error for the next field.

As I mentioned I'm new to BOINC and not very experienced. Could anyone offer any pointers about where I might be going wrong? I can see this script is very old ~10 years, is it possible that it no longer works in the latest version?

I've made very few changes to the default boinc-server-docker container, still using the latest tag on the images.

Thanks

**Comment by marius311** [comment]
Hi, quick question first. So I understand that you're running your server inside Docker via boinc-server-docker, but is the job you are trying to submit for Docker-based app (like described in [here](https://github.com/marius311/boinc-server-docker/blob/c6c9348ee6aeb5b01378c52bbfcc43cf35555717/docs/cookbook.md#running-jobs)), or is for a native app?

**Comment by madformuse** [comment]
It's for a native app. The application makes use of GPU processing and it's my understanding that the docker based apps can't do that. It is a boinc-server-docker server.

Sorry if this isn't the right place for the issue.

**Comment by marius311** [comment]
No worries, yea I think your problem is likely unrelated to boinc-server-docker then, you'll probably get a better response posting an Issue on the main BOINC repo. I'm not familiar with the script but your theory that its just outdated sounds pretty plausible to me.  Will close this issue for now.
