### ISSUE TITLE
Cannot create new user

### ISSUE THREAD

**Issue by JonathanStefanov** [marius311/boinc-server-docker#60]
Hello,
The server is working fine but when I try to sign up with the BOINC manager or the website it tells me that the email format is invalid.
![error](https://i.imgur.com/KHIB3FT.png)

I tested a lot of emails and none of them work, and they are normal email addresses such as test@gmail.com

**Comment by marius311** [comment]
Thanks for the report. I'm unable to reproduce your issue, unfortunately. Can you do a `docker-compose down -v` to delete all files are reset your server, and then try again, documenting every step you took, and then list them here? Also, can you let know exactly the version of boinc-server-docker you are using, and what OS you are on?

**Comment by JonathanStefanov** [comment]
Hello,
This morning I tested it out again and it works. I really don't understand what happened but well, it is working now!

Thank you for your answer.
