### ISSUE TITLE
Forbidden You don't have permission to access / on this server.

### ISSUE THREAD

**Issue by DapengLan** [marius311/boinc-server-docker#67]
I got the issue when try to open the browser with 127.0.0.1:80

Forbidden
You don't have permission to access / on this server.
Apache/2.4.25 (Debian) Server at 127.0.0.1 Port 80

I am using MAC here.

**Comment by marius311** [comment]
Sorry for the late reply, but in case you hadn't figured this out yet, the server is running at http://127.0.0.1/boincserver, rather than just http://127.0.0.1/.
