### ISSUE TITLE
Build error because of expired certificate

### ISSUE THREAD

**Issue by AenBleidd** [marius311/boinc-server-docker#73]
```
"Connecting to psysh.org (psysh.org)|185.199.111.153|:443... \u001b[0m\u001b[91mconnected.", "\u001b[0m\u001b[91mERROR: The certificate of 'psysh.org' is not trusted.", "ERROR: The certificate of 'psysh.org' has expired."
```

Full log is here:
https://github.com/BOINC/boinc/pull/4545/checks?check_run_id=3813645743

**Comment by AenBleidd** [comment]
Update:

This happens when running:
`docker-compose build --no-cache`
Log:
```
--2021-10-10 15:20:19--  https://psysh.org/psysh
Resolving psysh.org (psysh.org)... 185.199.111.153, 185.199.108.153, 185.199.109.153, ...
Connecting to psysh.org (psysh.org)|185.199.111.153|:443... connected.
ERROR: The certificate of 'psysh.org' is not trusted.
ERROR: The certificate of 'psysh.org' has expired.
```

**Comment by barton2526** [comment]
Suggested fix: 
change this line
https://github.com/marius311/boinc-server-docker/blob/master/images/apache/Dockerfile#L5

from
`FROM php:7.0.31-apache-stretch AS base`
to
`FROM php:7.3.31-apache-buster AS base`

Note that upgrading the PHP version and the OS base image may well break other things...

**Comment by marius311** [comment]
Fixed by https://github.com/marius311/boinc-server-docker/commit/28df02f75c07650c53a7c5f0a389118f48698fda

At some point we should probably upgrade the OS but I'd prefer to do that separately.

**Comment by barton2526** [comment]
> At some point we should probably upgrade the OS but I'd prefer to do that separately.

Can this be opened as an issue for tracking?

**Comment by AenBleidd** [comment]
@marius311, could you please create a new tag with this fix?
